name: CI/CD Pipeline

# Quando o workflow será executado
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: pegar o código do GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: configurar o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Passo 3: compilar e rodar testes JUnit
      - name: Build and run tests
        run: mvn clean test
        
  build-docker:
    runs-on: ubuntu-latest
    needs: build-and-test   # só roda se os testes passarem

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t vinicyusrs/petshop:latest .
          docker push vinicyusrs/petshop:latest